apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: blmszj5ur-nodejs 
  janus-idp.io/tekton: blmszj5ur-nodejs
  backstage.io/kubernetes-id: blmszj5ur-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: blmszj5ur-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  