apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: blmszj5ur-nodejs
  janus-idp.io/tekton: blmszj5ur-nodejs
  backstage.io/kubernetes-id: blmszj5ur-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: blmszj5ur-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
