apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: blmszj5ur-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: blmszj5ur-nodejs 
  name: blmszj5ur-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: blmszj5ur-nodejs 
